create table HEROES (
       ID bigint generated by default as identity,
        NOMBRE varchar(255) not null,
		GRUPO varchar(255),
        primary key (ID)
    );

alter table HEROES 
       add constraint UK_NMOBRE unique (nombre);
	   
INSERT INTO HEROES (NOMBRE, GRUPO) VALUES ('SPIDERMAN', 'MARVEL');
INSERT INTO HEROES (NOMBRE, GRUPO) VALUES ('SUPERMAN', 'DC');
INSERT INTO HEROES (NOMBRE, GRUPO) VALUES ('HULK', 'MARVEL');
INSERT INTO HEROES (NOMBRE, GRUPO) VALUES ('BATMAN', 'DC');